### ISSUE TITLE
244 - Home-Get started page links not working

### ISSUE THREAD

**Issue by Clearviction** [openseattle/clearviction-next#19]
> This issue was created using an Airtable automation. If there is information missing from the issue, more information may be available in the Airtable record, linked below.
## Airtable Record URL
https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/recvjZDRqIriLArQE
## Information
- Site URL - https://www.clearviction.org/get-started
- Browser - chrome
## Description 
Step 1: Documents 
Court Forms links not working (all)

Step 4: Court Hearing -> Financial Aid  -> Court Fees
First link not working

@erik, I think you're already working on this, correct? 
Ok if I just transition this to Ready for Engineering?

**Comment by e-papanicolas** [comment]
This issue has been resolved. The new href has replaced the broken link.
