### ISSUE TITLE
255 - Links replace our site instead of opening in new tab

### ISSUE THREAD

**Issue by Clearviction** [openseattle/clearviction-next#38]
> This issue was created using an Airtable automation. If there is information missing from the issue, more information may be available in the Airtable record, linked below.
## Airtable Record URL
https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/recDerOMhFIawlVA8
## Information
- Site URL - https://clearviction-next.vercel.app/why-vacate
- Browser - safari
## Description 
All the links in "Get Started" and "Why vacate" pages replace the existing CV tab, instead of opening in a new tab. - Judit

**Comment by e-papanicolas** [comment]
PR #41
