### ISSUE TITLE
271 - Missing back button 

### ISSUE THREAD

**Issue by Clearviction** [openseattle/clearviction-next#54]
> This issue was created using an Airtable automation. If there is information missing from the issue, more information may be available in the Airtable record, linked below.
## Airtable Record URL
https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/recE8X1ONzCUbXL21
## Information
- Site URL - https://clearviction-next.vercel.app/calculator/initial-misdemeanor
- Browser - chrome
## Description 
There is no back button throughout the calculator. This is consistent for each browser I used (Chrome, Firefox, Safari)

**Comment by e-papanicolas** [comment]
PR #58 fixes this issue.
