### ISSUE TITLE
266 - Bad routing when clicking away from calculator

### ISSUE THREAD

**Issue by Clearviction** [openseattle/clearviction-next#56]
> This issue was created using an Airtable automation. If there is information missing from the issue, more information may be available in the Airtable record, linked below.
## Airtable Record URL
https://airtable.com/appfJZShN8K4tcWHU/tblvBIYoi6TLmdRAv/rec0rUd9uCUK4DGrP
## Information
- Site URL - /calculator/<any-nav-link>
- Browser - other? - include in description
## Description 
If you are on the calculator, on any page, and click on a nav link, you are routed to '/calculator/<page-name>' which returns a 404. A second click on any of the nav items works fine and routes you back to the site, but I do think that this is happening due to the way we dynamically load all the calculator page routes by using the slug.

**Comment by e-papanicolas** [comment]
Closed as resolved.
